### ISSUE TITLE
User can sign up for a new account

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/Bet101#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When navigating to the site the user will be able to log in or sign up via a form. If the user hasn't created an account they can go to the sign up section and input a valid username and password, then submit it.

The form will dynamically update the password input turning green once the user has included 8 characters, a number, and a special character.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/25317196/196316275-202f4756-1bed-45c1-8919-b75297eeedf7.png)
![image](https://user-images.githubusercontent.com/25317196/196316363-a575fa9e-0bc6-44a0-b878-b97b210e42ab.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include a users table where username and hashedPassword will be stored

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive a POST request at the 'sign-up' route
- [x] check for valid user credentials
- [x] username must be unique 
  - [x] return an error to the client if the username is already taken
- [x] password must be 8 characters long and include 1 number and 1 special character
  - [x] return an error to the client if the password is invalid
- [x] hash the password with argon2
- [x] write the username and password to the database / user table
- [x] return a 201 status indicating the user was created successfully with userId, username, createdAt

### ⚡ Client Tasks

- [x] Create a navbar component
- [x] Include a home, log in, sign up, and betting 101 anchor tag
- [x] show some kind of logo on the left
- [x] create a login form component
- [x] create an odds bar below the nav when on a device larger than 768px
- [x] all buttons should be red
- [x] the component should be able to toggle between a log in and sign up page
- [x] the sign up page should include a username input
- [x] the sign up page should include a password input
- [x] the sign up page should include a submit button

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
