### ISSUE TITLE
User can see their available balance upon logging in

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/Bet101#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log into the app and see their available account balance.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is viewing the application on a mobile device the available balance will show in the burger drop down. When viewing on a desktop the account balance will display in the top right corner below the odds bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Account Balance](https://user-images.githubusercontent.com/25317196/208580370-f7249291-17ed-4a69-93f1-2ac3c28380db.png)

![NFL Odds (1)](https://user-images.githubusercontent.com/25317196/208582292-266fe571-15c4-4476-9990-fcabde286527.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include a field that includes the game time

### ☁️ Server Tasks

- [x] Update server route for placing a bet to update the game time field in the bets table
- [x] Calculate the number of hours, minutes, and seconds until game time
- [x] Add 3 hours to that number
- [x] Set a callback that sends a request to the odds api at that time to check if that game is over
- [x] If the game is over record score and game information and calculate if the bet was won
- [x] If the game is not over set a callback function to check again every 30 minutes
- [x] Create a get route that simply returns the users current account balance by querying the users table
- [x] create functions to calculate if a placed bet was won relative to the outcome of a game
- [x] create a function(s) to handle a tie, which results in the user getting their bet amount back
- [x] subtract a bet amount from the user's account immediately after placing a bet
- [x] always check to make sure game start time is after the current time (so users cannot retroactively add a bet record after game outcome occurs)
- [x] decode the token that is included on requests to find user information

### ⚡ Validity Checks

- [x] Check that every request contains a valid userId
- [x] Check that bet amount does not exceed current account balance
- [x] Check that the data types of place bet post request are correct (i.e. all integers are integers and not strings)
- [x] Set correctly on the client side first, then check on the server

### ⚡ Client Tasks

- [x] Update the navbar component to include calculated account balance in the burger dropdown on mobile
- [x] Add account balance to main page below odds bar when viewing on desktop

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
