### ISSUE TITLE
User can deposit "money"

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/Bet101#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can deposit "money".

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can navigate to the "My Bets" page and find a deposit button there. The user can deposit more funds once every 24 hours, and not to exceed the deposit amount + current account balance. Once the deposit value is submitted the user's account will now have that amount listed as the account value.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/25317196/196317603-f6552280-8eac-4c98-98a5-405c09561918.png)

![image](https://user-images.githubusercontent.com/25317196/196317563-92b65ff7-26d5-4cce-a535-7c733431111b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update database to store initial deposit amount associated with a specific user
- [x] Update schema to include a time of last deposit

### ☁️ Server Tasks

- [x] Create a deposit route that can only be accessed once a user is logged in
- [x] Check the database for time of last deposit, and return an error if if the the time of last deposit is less than 24 hours
- [x] Check that deposit amount is a valid number between 1 and 10,000
- [x] Check that the user's total account balance cannot exceed $10,000 total (current balance + deposit amount)

### ⚡ Client Tasks

- [x] Create a deposit form component
- [x] Validate that the input is a number greater than 0 and less than the current account balance + deposit amount
- [x] If the user tries to deposit a value that returns as NaN then provide a form error 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
