### ISSUE TITLE
User can filter odds by sport

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/Bet101#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to select a specific sport they want to place a bet for. Currently there will only be 3 sport options (NBA basketball, NFL football, MLB baseball). If the sport is out of season a message will pop up showing that the sport is out of season.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon logging in the user will see 3 options at the top of the viewport. When you click on an option that will load the currently available odds for the sport.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Burger Menu](https://user-images.githubusercontent.com/25317196/207917636-1b55b521-96fc-491e-a240-a884c56d87ec.png)

![NFL Odds](https://user-images.githubusercontent.com/25317196/207917730-080db909-e469-44da-b26e-702769a52198.png)

Desktop screens

![NFL Odds (1)](https://user-images.githubusercontent.com/25317196/207917874-09e4ced0-d82b-4866-9845-1f7dde7a2298.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to hold each of the sports a user can bet on
- [x] Include an image or icon that represents the sport
- [x] create an anchor element that changes the url hash to the designated sport
- [x] use a hashchange event callback to re-render the page with appropriate sport odds

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
