### ISSUE TITLE
User can place a bet

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/Bet101#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can place a bet for a given sport.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click any of 3 types of odds for a given sport. Clicking on an odd will bring up a modal that allows the user to enter an amount of "money" they want to bet, and also see the potential winnings from placing that bet. The user can change the bet amount and see the updated potential winnings. When ready, the user can click submit and the bet will be placed. The screen for the modal will change to indicate the user has successfully placed a bet.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Bet Slip](https://user-images.githubusercontent.com/25317196/207920373-608955ce-5955-49a0-b6a0-edf1b8a900c3.png)
![Place Bet - Success](https://user-images.githubusercontent.com/25317196/207920371-aba2f4e8-0570-4f15-ac60-af60a7923c5b.png)

Desktop screens

![Place Bet](https://user-images.githubusercontent.com/25317196/207920751-4a7c8700-7ec4-4ec6-90c8-7413f29bf4c5.png)
![Successful Bet](https://user-images.githubusercontent.com/25317196/207920763-08d84363-fad5-4703-b65b-48b4728bf50a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Database will store the bet information in primary 'bets' table
- [x] Database will then store a more detailed record of the bet in the specific bet type table i.e. spread, moneyline, or total
- [x] Database will store the bet information with correct linkage to user
- [x] Each record in the primary bet table will have a unique id and that id will be the linkage to the specific bet type table
- [x] Each specific bet record will have its own unique id, and a foreign key of primary bet id

### ☁️ Server Tasks

- [x] Update `server/index.js` to listen on a route for submitting bets
- [x] Express will submit bet info to appropriate database table

### ⚡ Client Tasks

- [x] Create a click listener for each odds table
- [x] Create a modal component that pops up when an odd type is clicked
- [x] Modal should contain a form that prepopulates information about the bet including game info
- [x] User should be able to enter an amount to bet
- [x] Modal will update the potential winnings for said bet
- [x] User can submit bet to the server
- [x] By clicking a certain bet type (spread, moneyline, totals) this will store the bet in a separate table
- [x] Close the modal upon successful bet placement

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
