### ISSUE TITLE
User can see their entire bet history

### ISSUE THREAD

**Issue by gquathamer** [gquathamer/Bet101#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their entire bet history which includes won/lost/pending bets
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to select a 'My Bets' option from the mobile dropdown or the desktop navbar. This will take them to a new page that shows in a table the users entire bet history along with current account balance.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

When viewing on a mobile device the user will be able to see several options in the dropdown. One of them will take them to 'My Account' which will allow the user to deposit more funds or simply view their bet history:
![Account Page](https://user-images.githubusercontent.com/25317196/213067589-3a0130ea-d966-4dc9-9165-437db4110f92.png)

![Bet History](https://user-images.githubusercontent.com/25317196/213067590-69c0826a-6ebe-4571-ad09-1b1f82006bee.png)

![Account Balance (1)](https://user-images.githubusercontent.com/25317196/213067591-33ae04e4-189b-4cf6-bc24-080946b7b04b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Write a query that pulls all bets from the 'bets' table, joined to the specific bet type. For example, if the bet type was a spread bet then join the specific spread bet data from the 'spreadBet' table.

### ☁️ Server Tasks

- [x] Create a route that listens for requests, and queries the database for all bet history
- [x] Return the bet history in JSON

### ⚡ Client Tasks

- [x] Create a page specifically for user account information
The user account page should include the following:
- [x] Account balance
- [x] Bet history table
- [x] Bet history table will have one row for each bet placed, the outcome, any winnings, and game information 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
